export const currentUser = {
  id: "EMP001",
  name: "Rajesh Kumar",
  email: "rajesh.kumar@company.com",
  role: "super_admin",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh",
  department: "Human Resources",
  designation: "HR Director",
};

export const employees = [
  {
    id: "1",
    employeeCode: "EMP001",
    camAttendanceId: "CAM001",
    name: "Rajesh Kumar",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh",
    dob: "1985-03-15",
    gender: "Male",
    bloodGroup: "O+",
    mobile: "9876543210",
    alternateMobile: "9876543211",
    email: "rajesh.kumar@company.com",
    address: "123 MG Road, Bangalore, Karnataka 560001",
    department: "Human Resources",
    designation: "HR Director",
    reportingManager: "CEO",
    joiningDate: "2018-01-15",
    employmentType: "Full Time",
    status: "Active",
    emergencyContact: "Priya Kumar - 9876543299",
    bankName: "HDFC Bank",
    accountNumber: "XXXX1234",
    pan: "ABCDE1234F",
    aadhaar: "XXXX-XXXX-1234",
  },
  {
    id: "2",
    employeeCode: "EMP002",
    camAttendanceId: "CAM002",
    name: "Priya Sharma",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    dob: "1990-07-22",
    gender: "Female",
    bloodGroup: "A+",
    mobile: "9876543220",
    alternateMobile: "",
    email: "priya.sharma@company.com",
    address: "456 Brigade Road, Bangalore, Karnataka 560025",
    department: "Engineering",
    designation: "Senior Engineer",
    reportingManager: "Amit Patel",
    joiningDate: "2019-06-01",
    employmentType: "Full Time",
    status: "Active",
    emergencyContact: "Ravi Sharma - 9876543298",
    bankName: "ICICI Bank",
    accountNumber: "XXXX5678",
    pan: "FGHIJ5678K",
    aadhaar: "XXXX-XXXX-5678",
  },
  {
    id: "3",
    employeeCode: "EMP003",
    camAttendanceId: "CAM003",
    name: "Amit Patel",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amit",
    dob: "1988-11-08",
    gender: "Male",
    bloodGroup: "B+",
    mobile: "9876543230",
    alternateMobile: "9876543231",
    email: "amit.patel@company.com",
    address: "789 Indiranagar, Bangalore, Karnataka 560038",
    department: "Engineering",
    designation: "Team Lead",
    reportingManager: "CTO",
    joiningDate: "2017-03-20",
    employmentType: "Full Time",
    status: "Active",
    emergencyContact: "Sunita Patel - 9876543297",
    bankName: "SBI",
    accountNumber: "XXXX9012",
    pan: "KLMNO9012P",
    aadhaar: "XXXX-XXXX-9012",
  },
  {
    id: "4",
    employeeCode: "EMP004",
    camAttendanceId: "CAM004",
    name: "Sneha Reddy",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha",
    dob: "1992-04-18",
    gender: "Female",
    bloodGroup: "AB+",
    mobile: "9876543240",
    alternateMobile: "",
    email: "sneha.reddy@company.com",
    address: "321 Koramangala, Bangalore, Karnataka 560034",
    department: "Finance",
    designation: "Accountant",
    reportingManager: "Rajesh Kumar",
    joiningDate: "2020-08-10",
    employmentType: "Full Time",
    status: "Active",
    emergencyContact: "Venkat Reddy - 9876543296",
    bankName: "Axis Bank",
    accountNumber: "XXXX3456",
    pan: "QRSTU3456V",
    aadhaar: "XXXX-XXXX-3456",
  },
  {
    id: "5",
    employeeCode: "EMP005",
    camAttendanceId: "CAM005",
    name: "Vikram Singh",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram",
    dob: "1987-09-25",
    gender: "Male",
    bloodGroup: "O-",
    mobile: "9876543250",
    alternateMobile: "9876543251",
    email: "vikram.singh@company.com",
    address: "654 Whitefield, Bangalore, Karnataka 560066",
    department: "Sales",
    designation: "Sales Executive",
    reportingManager: "Director Sales",
    joiningDate: "2021-02-14",
    employmentType: "Full Time",
    status: "Active",
    emergencyContact: "Anita Singh - 9876543295",
    bankName: "Kotak Bank",
    accountNumber: "XXXX7890",
    pan: "WXYZ7890A",
    aadhaar: "XXXX-XXXX-7890",
  },
  {
    id: "6",
    employeeCode: "EMP006",
    camAttendanceId: "CAM006",
    name: "Ananya Iyer",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya",
    dob: "1993-12-03",
    gender: "Female",
    bloodGroup: "A-",
    mobile: "9876543260",
    alternateMobile: "",
    email: "ananya.iyer@company.com",
    address: "987 Jayanagar, Bangalore, Karnataka 560041",
    department: "Marketing",
    designation: "Marketing Executive",
    reportingManager: "Marketing Head",
    joiningDate: "2022-05-01",
    employmentType: "Full Time",
    status: "On Leave",
    emergencyContact: "Krishna Iyer - 9876543294",
    bankName: "HDFC Bank",
    accountNumber: "XXXX2345",
    pan: "BCDEF2345G",
    aadhaar: "XXXX-XXXX-2345",
  },
  {
    id: "7",
    employeeCode: "EMP007",
    camAttendanceId: "CAM007",
    name: "Rahul Mehta",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul",
    dob: "1991-06-12",
    gender: "Male",
    bloodGroup: "B-",
    mobile: "9876543270",
    alternateMobile: "9876543271",
    email: "rahul.mehta@company.com",
    address: "147 HSR Layout, Bangalore, Karnataka 560102",
    department: "IT Support",
    designation: "IT Support Engineer",
    reportingManager: "IT Head",
    joiningDate: "2020-11-20",
    employmentType: "Full Time",
    status: "Active",
    emergencyContact: "Meera Mehta - 9876543293",
    bankName: "ICICI Bank",
    accountNumber: "XXXX6789",
    pan: "HIJKL6789M",
    aadhaar: "XXXX-XXXX-6789",
  },
  {
    id: "8",
    employeeCode: "EMP008",
    camAttendanceId: "CAM008",
    name: "Kavitha Nair",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kavitha",
    dob: "1989-02-28",
    gender: "Female",
    bloodGroup: "O+",
    mobile: "9876543280",
    alternateMobile: "",
    email: "kavitha.nair@company.com",
    address: "258 Electronic City, Bangalore, Karnataka 560100",
    department: "Operations",
    designation: "Operations Manager",
    reportingManager: "COO",
    joiningDate: "2016-09-05",
    employmentType: "Full Time",
    status: "Active",
    emergencyContact: "Suresh Nair - 9876543292",
    bankName: "SBI",
    accountNumber: "XXXX0123",
    pan: "NOPQR0123S",
    aadhaar: "XXXX-XXXX-0123",
  },
];

export const dashboardStats = {
  totalEmployees: 248,
  presentToday: 215,
  absentToday: 18,
  onLeave: 12,
  lateEmployees: 8,
  attendancePercentage: 86.7,
};

export const weeklyAttendance = [
  { day: "Mon", present: 220, absent: 15, leave: 13 },
  { day: "Tue", present: 225, absent: 12, leave: 11 },
  { day: "Wed", present: 218, absent: 18, leave: 12 },
  { day: "Thu", present: 222, absent: 14, leave: 12 },
  { day: "Fri", present: 215, absent: 20, leave: 13 },
  { day: "Sat", present: 180, absent: 8, leave: 5 },
];

export const departmentAttendance = [
  { department: "Engineering", percentage: 92 },
  { department: "HR", percentage: 95 },
  { department: "Finance", percentage: 88 },
  { department: "Sales", percentage: 85 },
  { department: "Marketing", percentage: 90 },
  { department: "Operations", percentage: 87 },
  { department: "IT Support", percentage: 91 },
];

export const monthlyTrend = [
  { month: "Jan", attendance: 89 },
  { month: "Feb", attendance: 91 },
  { month: "Mar", attendance: 88 },
  { month: "Apr", attendance: 92 },
  { month: "May", attendance: 90 },
  { month: "Jun", attendance: 87 },
];

export const recentActivities = [
  { id: 1, type: "new_employee", message: "New employee John Doe joined Engineering", time: "2 hours ago", icon: "user-plus" },
  { id: 2, type: "leave_request", message: "Ananya Iyer applied for Casual Leave (3 days)", time: "3 hours ago", icon: "calendar" },
  { id: 3, type: "attendance_correction", message: "Attendance correction for EMP003 on 02-Jun-2026", time: "5 hours ago", icon: "edit" },
  { id: 4, type: "leave_request", message: "Vikram Singh leave request approved by Manager", time: "6 hours ago", icon: "check" },
  { id: 5, type: "new_employee", message: "New employee Sarah Wilson joined Marketing", time: "1 day ago", icon: "user-plus" },
];

export const notifications = [
  { id: 1, title: "Leave Request Pending", message: "3 leave requests awaiting your approval", time: "10 min ago", read: false },
  { id: 2, title: "Attendance Alert", message: "8 employees marked late today", time: "30 min ago", read: false },
  { id: 3, title: "New Joiner", message: "John Doe onboarding scheduled for tomorrow", time: "1 hour ago", read: true },
  { id: 4, title: "Report Generated", message: "May 2026 attendance report is ready", time: "2 hours ago", read: true },
];

export const leaveBalances = {
  casualLeave: { total: 12, used: 4, remaining: 8 },
  sickLeave: { total: 10, used: 2, remaining: 8 },
  earnedLeave: { total: 15, used: 5, remaining: 10 },
  optionalHoliday: { total: 2, used: 1, remaining: 1 },
  compOff: { total: 3, used: 0, remaining: 3 },
};

export const leaveRequests = [
  { id: 1, employeeCode: "EMP006", employeeName: "Ananya Iyer", department: "Marketing", leaveType: "Casual Leave", from: "2026-06-10", to: "2026-06-12", days: 3, reason: "Family function", status: "Pending", managerStatus: "Approved", hrStatus: "Pending" },
  { id: 2, employeeCode: "EMP005", employeeName: "Vikram Singh", department: "Sales", leaveType: "Sick Leave", from: "2026-06-03", to: "2026-06-04", days: 2, reason: "Medical appointment", status: "Approved", managerStatus: "Approved", hrStatus: "Approved" },
  { id: 3, employeeCode: "EMP002", employeeName: "Priya Sharma", department: "Engineering", leaveType: "Earned Leave", from: "2026-06-20", to: "2026-06-25", days: 6, reason: "Vacation", status: "Pending", managerStatus: "Pending", hrStatus: "Pending" },
  { id: 4, employeeCode: "EMP007", employeeName: "Rahul Mehta", department: "IT Support", leaveType: "Comp Off", from: "2026-06-07", to: "2026-06-07", days: 1, reason: "Worked on holiday", status: "Rejected", managerStatus: "Rejected", hrStatus: "N/A" },
];

export const holidays = [
  { date: "2026-01-26", name: "Republic Day" },
  { date: "2026-03-08", name: "Holi" },
  { date: "2026-08-15", name: "Independence Day" },
  { date: "2026-10-02", name: "Gandhi Jayanti" },
  { date: "2026-12-25", name: "Christmas" },
];

export const attendanceRecords = employees.map((emp) => ({
  employeeCode: emp.employeeCode,
  employeeName: emp.name,
  department: emp.department,
  present: false,
  absent: false,
  halfDay: false,
  leave: emp.status === "On Leave",
  remarks: "",
}));

export const employeeAttendance = [
  { date: "2026-06-01", status: "Present", inTime: "09:02", outTime: "18:15" },
  { date: "2026-06-02", status: "Present", inTime: "09:15", outTime: "18:30" },
  { date: "2026-06-03", status: "Late", inTime: "09:45", outTime: "18:00" },
  { date: "2026-06-04", status: "Present", inTime: "08:55", outTime: "18:10" },
  { date: "2026-06-05", status: "Present", inTime: "09:00", outTime: "18:20" },
];

export const employeeLeaves = [
  { type: "Casual Leave", from: "2026-03-10", to: "2026-03-11", days: 2, status: "Approved" },
  { type: "Sick Leave", from: "2026-04-05", to: "2026-04-05", days: 1, status: "Approved" },
  { type: "Earned Leave", from: "2026-05-20", to: "2026-05-22", days: 3, status: "Approved" },
];

export const activityLogs = [
  { action: "Profile Updated", by: "HR Admin", date: "2026-05-15", details: "Contact details updated" },
  { action: "Department Changed", by: "Super Admin", date: "2026-04-01", details: "Moved from Sales to HR" },
  { action: "Salary Revision", by: "HR Director", date: "2026-03-01", details: "Annual increment applied" },
  { action: "Document Uploaded", by: "Employee", date: "2026-02-10", details: "PAN card uploaded" },
];

export const COMPANY_NAME = "VLJ Treasures Pvt. Ltd.";
